-- BookMySeat PostgreSQL Schema

------------------------------
-- DATABASE :: auth_db
-- OWNER :: auth-service
------------------------------

SELECT 'CREATE DATABASE "auth_db"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'auth_db')\gexec

\c "auth_db"

CREATE TABLE IF NOT EXISTS "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    role INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "user_details" (
    user_id INT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    age INTEGER,
    gender INT
    );

------------------------------
-- DATABASE :: show_db
-- OWNER :: show-service
------------------------------

SELECT 'CREATE DATABASE "show_db"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'show_db')\gexec

\c "show_db"

CREATE TABLE IF NOT EXISTS "event" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    duration_minutes INT NOT NULL,
    category INT,
    age_rating INT NOT NULL,
    release_date DATE
);

CREATE TABLE IF NOT EXISTS "venue" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    admin_id INT NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "auditorium" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    capacity INTEGER NOT NULL,
    venue_id INT NOT NULL REFERENCES "venue"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "show" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    event_id INT NOT NULL REFERENCES "event"(id) ON DELETE CASCADE,
    auditorium_id INT NOT NULL REFERENCES "auditorium"(id) ON DELETE CASCADE
);

------------------------------
-- DATABASE :: booking_db
-- OWNER :: booking-service
------------------------------

SELECT 'CREATE DATABASE "booking_db"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'booking_db')\gexec

\c "booking_db"

CREATE TABLE IF NOT EXISTS "show_seat" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    show_id INT NOT NULL,
    price NUMERIC(5, 2) NOT NULL,
    state VARCHAR(50) NOT NULL,
    locked_by INT,
    locked_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "booking" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    show_id INT NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    state VARCHAR(50) NOT NULL,
    time TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "show_booking" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    booking_id INT NOT NULL REFERENCES "booking"(id) ON DELETE CASCADE,
    show_seat_id INT NOT NULL REFERENCES "show_seat"(id) ON DELETE CASCADE
);

------------------------------
-- DATABASE :: payment_db
-- OWNER :: payment-service
------------------------------

SELECT 'CREATE DATABASE "payment_db"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'payment_db')\gexec

\c "payment_db"

CREATE TABLE IF NOT EXISTS "transaction" (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    state VARCHAR(50) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    booking_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
