spring.datasource.url=jdbc:postgresql://localhost:5432/query_db
spring.datasource.username=bmsuser
spring.datasource.password=bXlwYXNzd29yZA
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,prometheus